### ISSUE TITLE
Contao Manager

### ISSUE THREAD

**Issue by chriza** [agoat/contao-autoprefixer-bundle#4]
Hallo,

haben Sie eventuell eine Version in Planung, die über den Contao Manager installiert werden kann?

**Comment by agoat** [comment]
Die Verwendung des _Contao Managers_ ist geplant, allerdings wird das noch etwas dauern. 
Da der Manager noch stark in der Entwicklung steckt (aktuell Beta10), habe ich bisher noch mit der Umsetzung für meine Erweiterung gewartet.

**Comment by agoat** [comment]
Die Autoprefixer Erweiterung kann jetzt (ab `Version 1.2.0`) auch über den Contao Manager installiert werden.
