### ISSUE TITLE
Angabe des node.js-Pfades neben Browser query

### ISSUE THREAD

**Issue by dennis-sagasser** [agoat/contao-autoprefixer-bundle#6]
Hallo Arne,

super nützliche Extension. Vielen Dank dafür! 

Ich habe eine eigene Erweiterung nach Contao-3-Schema gebastelt. Diese soll u.a. dem Seitenlayout ein Feld für den node.js-Pfad hinzufügen, da auf dem Server kein Alias dafür verfügbar ist. Nun wird contao-autoprefixer offensichtlich nicht vor meiner Erweiterung geladen, wodurch z.B. meine dca-Änderungen keine Wirkung zeigen. Gibt es eine Möglichkeit, die Erweiterung zu laden (autoload.ini requires funzt ja nicht, weil sie ein Bundle ist)? Falls nicht, wäre das zusätzliche Feld ein denkbares Feature? 

Besten Dank
Dennis

**Comment by agoat** [comment]
Diese Erweiterung ist für Contao 4 entwickelt. 
Es gibt die Möglichkeit die Reihenfolge bzw. Abhängigkeit von anderen Bundles zu definieren. Dazu müsste deine Erweiterung aber ebenfalls über das Contao-Manager-Plugin eingebunden werden.

Ich bin bisher immer davon ausgegangen, dass wenn Node.js installiert ist, immer ein **node** Alias!?

Es sollte aber kein Problem sein, den *node.js* Pfad konfigurierbar zu machen. Das würde ich allerdings eher zu den *Settings* packen oder gleich als *contao parameter* realisieren.
