### ISSUE TITLE
Conflict with symfony/Framework-Bundle 4.4* 

### ISSUE THREAD

**Issue by kgansberger** [agoat/contao-autoprefixer-bundle#7]
danke für die Erweiterung! 
Ist require symfony/framework-bundle 4.4* möglich ? Bekomme Fehler bei Installation mit Cloud Composer.

![image](https://user-images.githubusercontent.com/1162770/99911629-086efb00-2cf6-11eb-89b1-d0aed91d0ba6.png)

**Comment by agoat** [comment]
Die Erweiterung ist (noch) nicht mit der neuesten Contao-Version kompatibel. Ich hatte es zuletzt nur bis Contao 4.6 getestet. Bei Contao 4.9 wurde u.a. auch auf eine neuere Symfony-Framework Version gewechselt. Daher kommt es zu Konflikten bei der Installation.

Ich hoffe diese Erweiterung bald mit der neuesten Contao-Version kompatibel machen zu können.

**Comment by kgansberger** [comment]
das wär fein! danke +++

**Comment by agoat** [comment]
Die Version 2.0.0 ist jetzt mit der neuesten Contao Version kompatibel (Contao 4.10 und Contao 4.9 lts).
